<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Answer' => '回答',
    'Broadcaster' => '用户',
    'Follow' => '关注',
    'Followed' => '已关注',
    'Follower' => '关注',
    'His' => '他',
    'Lives' => '直播',
    'My' => '我',
    'Questions' => '问题',
    'Support' => '赞同',
    'The request has not been applied because it lacks valid authentication credentials for the target resource.' => '请登录。',
    'Users' => '用户',
    'records' => '条记录',
    '{who} followed {what}' => '{who}关注的{what}',
    '{who} follower' => '{who}的粉丝',
];
